BASE:
  - configs/ShapeNet/shapenet_uncond.yaml

DATA:
  train:
    name: &name objaverse
    points_scale: &points_scale 1.0
    location: &location data/Objaverse/datasets_512
    filelist: &filelist data/Objaverse/filelist/objaverse_5w_train.txt
    load_text: &load_text True
    text_location: &text_location data/Objaverse/filelist/Cap3D_automated_Objaverse_highquality.csv
    caption: &caption cap3d

  test:
    name: *name
    points_scale: *points_scale
    location: *location
    filelist: data/Objaverse/filelist/objaverse_5w_test.txt
    load_text: *load_text
    text_location: *text_location
    caption: *caption
    shuffle: False
    text_prompt: A 3D model.

    
MODEL:
  OctGPT:
    num_embed: 1152
    patch_size: 1024
    dilation: 8
    buffer_size: 77
    random_flip: 0.2
    pos_emb_type: AbsPosEmb
    norm_type: RMSNorm
    num_iters: [64, 128, 128, 256]
    condition_type: text
    condition_encoder: clip
    condition_policy: cross_attn
    context_dim: 768