BASE:
  - configs/ShapeNet/shapenet_vae.yaml

SOLVER:
  max_epoch: 100
  test_every_epoch: 1

DATA:
  train:
    name: &name objaverse

    # octree building
    depth: &depth 9
    full_depth: &full_depth 3
    points_scale: &points_scale 0.5  # the scale of point clouds

    # sdf & color samples
    volume_sample_num: &volume_sample_num 10000
    surface_sample_num: &surface_sample_num 10000
    tsdf: &tsdf 0.05

    # data loading
    location: &location data/Objaverse/ObjaverseXL_sketchfab/datasets_512
    filelist: data/Objaverse/ObjaverseXL_sketchfab/filelist/train_obja.txt

  test:
    name: *name

    # octree building
    depth: *depth
    full_depth: *full_depth
    points_scale: *points_scale

    # sdf & color samples
    volume_sample_num: *volume_sample_num
    surface_sample_num: *surface_sample_num
    tsdf: *tsdf

    # data loading
    location: *location
    filelist: data/Objaverse/ObjaverseXL_sketchfab/filelist/test_obja.txt


MODEL:
  name: vqvae_huge
  in_channels: 4
  embedding_channels: 64
  quantizer_type: bsq
  feature: ND
  rnd_flip: 0.0


LOSS:
  name: shape
  vae_weight: 1.0
  reg_loss_type: sdf_reg_loss