BASE:
  - configs/ShapeNet/shapenet_octar.yaml

DATA:
  train:
    name: &name objaverse
    points_scale: &points_scale 1.0
    location: &location data/Objaverse/ObjaverseXL_sketchfab/datasets_512
    filelist: &filelist data/Objaverse/filelist/ObjaverseXL_sketchfab.txt
    load_text: &load_text True
    text_location: &text_location data/Objaverse/filelist/ObjaverseXL_sketchfab.csv
    caption: &caption trellis

  test:
    name: *name
    points_scale: *points_scale
    location: *location
    filelist: data/Objaverse/filelist/ObjaverseXL_sketchfab_test.txt
    load_text: *load_text
    text_location: *text_location
    caption: *caption
    shuffle: False
    # text_prompt: 3D model of a winged female demon

    
MODEL:
  OctGPT:
    buffer_size: 77
    random_flip: 0.2
    num_iters: [64, 128, 128, 256]
    condition_type: text
    condition_encoder: clip
    condition_policy: cross_attn
    context_dim: 768