BASE:
  - configs/ShapeNet/shapenet_octar.yaml

DATA:
  train:
    filelist: &filelist data/ShapeNet/filelist/train_chair.txt
    load_text: &load_text True
    text_location: &text_location data/ShapeNet/filelist/captions.tablechair.csv

  test:
    filelist: *filelist
    load_text: *load_text
    text_location: *text_location
    
MODEL:
  OctGPT:
    buffer_size: 77
    condition_type: text
    condition_encoder: clip
    condition_policy: cross_attn
    context_dim: 768
    cfg_prob: 0.1
    cfg_scale: 1.0