SOLVER:
  gpu: 0,
  run: train

  logdir: logs/test/shapenet_octgpt
  max_epoch: 400
  test_every_epoch: 1
  log_per_iter: 50
  ckpt_num: 10
  expand_ckpt: False
  port: 10001

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.0001           # default value of adamw
  rand_seed: 0
  use_amp: True

  # learning rate
  lr_type: constant
  step_size: (160,240)

  # sdf
  resolution: 256       # the resolution used for marching cubes
  save_sdf: False       # save the sdfs in evaluation
  sdf_scale: 0.9        # the scale of sdfs

DATA:
  train:
    name: &name shapenet

    # octree building
    depth: &depth 8
    full_depth: &full_depth 3
    points_scale: &points_scale 0.5  # the scale of point clouds

    # sdf & color samples
    volume_sample_num: &volume_sample_num 10000
    surface_sample_num: &surface_sample_num 10000
    max_points: &max_points 120000
    tsdf: &tsdf 0.05

    # no data augmentation
    distort: &distort False

    # data loading
    location: &location data/ShapeNet/dataset_256
    filelist: &filelist data/ShapeNet/filelist/train_airplane.txt
    load_pointcloud: &load_pointcloud True
    load_sdf: &load_sdf False
    batch_size: 1
    shuffle: True

  test:
    name: *name

    # octree building
    depth: *depth
    full_depth: *full_depth
    points_scale: *points_scale

    # sdf & color samples
    volume_sample_num: *volume_sample_num
    surface_sample_num: *surface_sample_num
    max_points: *max_points
    tsdf: *tsdf

    # no data augmentation
    distort: *distort

    # data loading
    location: *location
    filelist: data/ShapeNet/filelist/test_airplane.txt
    category: airplane
    batch_size: 1
    load_pointcloud: *load_pointcloud
    load_sdf: *load_sdf
    shuffle: False

MODEL:
  depth: *depth
  full_depth: *full_depth
  depth_stop: 6
  vqvae_ckpt: saved_ckpt/vqvae_huge_im5_bsq32_200epoch.pth
  find_unused_parameters: True
  model_name: OctGPT

  VQVAE:
    name: vqvae_large
    in_channels: 4
    embedding_channels: 32
    quantizer_type: bsq
    feature: ND
  
  OctGPT:
    num_embed: 768
    num_heads: 8
    num_blocks: 24
    num_classes: 1
    split_size: 2
    patch_size: 2048
    dilation: 2
    buffer_size: 64
    drop_rate: 0.1
    pos_emb_type: SinPosEmb
    norm_type: LayerNorm
    use_checkpoint: True
    use_swin: True
    random_flip: 0.1
    mask_ratio_min: 0.5
    remask_stage: 0.7
    start_temperature: [1.0, 1.2, 0.5, 0.5]
    num_iters: [64, 128, 128, 256]
    condition_type: none
    condition_encoder: vit
    condition_policy: concat
    context_dim: 512

