BASE:
  - configs/shapenet_octar.yaml

DATA:
  train:
    name: &name objaverse
    points_scale: &points_scale 1.0
    location: &location data/Objaverse/objaverse_5w
    filelist: &filelist data/Objaverse/filelist/objaverse_5w_train.txt
    load_text: &load_text True
    text_location: &text_location data/Objaverse/filelist/Cap3D_automated_Objaverse_highquality.csv

  test:
    name: *name
    points_scale: *points_scale
    location: *location
    filelist: data/Objaverse/filelist/objaverse_5w_val.txt
    load_text: *load_text
    text_location: *text_location
    shuffle: False
    # text_prompt: 3D model of a winged female demon

    
MODEL:
  OctGPT:
    buffer_size: 77
    random_flip: 0.5
    num_iters: [64, 128, 128, 256]
    condition_type: text
    condition_encoder: clip
    condition_policy: cross_attn
    context_dim: 768
    cfg_prob: 0.1
    cfg_scale: 1.0