SOLVER:
  gpu: 0,
  run: train

  logdir: logs/shapenet_vae/vqvae
  max_epoch: 300
  test_every_epoch: 20
  log_per_iter: 20
  ckpt_num: 40
  port: 10001

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  step_size: (160,240)


DATA:
  train:
    name: &name shapenet

    # octree building
    depth: &depth 8
    full_depth: &full_depth 3
    point_scale: &point_scale 0.5  # the scale of point clouds

    # sdf & color samples
    volume_sample_num: &volume_sample_num 10000
    surface_sample_num: &surface_sample_num 10000

    # data augmentation
    distort: False

    # data loading
    location: &location data/ShapeNet/dataset_10w
    filelist: data/ShapeNet/filelist/train_airplane.txt
    load_pointcloud: True
    load_sdf: True
    batch_size: 2
    shuffle: True

  test:
    name: *name

    # octree building
    depth: *depth
    full_depth: *full_depth
    point_scale: *point_scale

    # sdf & color samples
    volume_sample_num: *volume_sample_num
    surface_sample_num: *surface_sample_num

    # data augmentation
    distort: False

    # data loading
    location: *location
    filelist: data/ShapeNet/filelist/test_airplane.txt
    batch_size: 1
    load_pointcloud: True
    load_sdf: True
    shuffle: False


MODEL:
  name: vae

  in_channels: 4
  out_channels: 4
  embedding_sizes: 128
  embedding_channels: 256
  feature: ND

LOSS:
  name: shapenet_vae_loss
  vq_weight: 0.5
  mpu_keys: [7, 8]
  mpu_weights: [1.0, 1.0]
