BASE:
  - configs/shapenet_octar.yaml

DATA:
  train:
    load_sketch: &load_sketch False
    load_image: &load_image True
    # image_location: &image_location data/ShapeNet/sketch_256
    image_location: &image_location data/ShapeNet/fid_images/car/view_0

  test:
    load_sketch: *load_sketch
    load_image: *load_image
    image_location: *image_location
    
MODEL:
  OctGPT:
    buffer_size: 257
    condition_type: image
    condition_encoder: dinov2
    condition_policy: cross_attn
    context_dim: 1024
    cfg_prob: 0.0