BASE:
  - configs/shapenet_vae.yaml

SOLVER:
  run: evaluate
  logdir: logs/shapenet_vae_eval/vqvae
  # ckpt: logs/shapenet_vae/vqvae_airplane_b8/best_model.pth


DATA:
  test:
    # for extracting meshes
    resolution: 300       # the resolution used for marching cubes
    save_sdf: False       # save the sdfs in evaluation
    sdf_scale: 0.9        # the scale of sdfs
