SOLVER:
  gpu: 0,
  run: train

  logdir: logs/shapenet_vae/vae
  max_epoch: 300
  test_every_epoch: 20
  log_per_iter: 50
  ckpt_num: 40
  port: 10001

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: constant
  step_size: (160,240)

  # sdf
  resolution: 128       # the resolution used for marching cubes
  save_sdf: False       # save the sdfs in evaluation
  sdf_scale: 0.9        # the scale of sdfs

DATA:
  train:
    name: &name shapenet_vae

    # octree building
    depth: &depth 8
    full_depth: &full_depth 4
    point_scale: &point_scale 0.5  # the scale of point clouds

    # sdf & color samples
    volume_sample_num: &volume_sample_num 10000
    surface_sample_num: &surface_sample_num 10000

    # no data augmentation
    distort: &distort False

    # data loading
    location: &location data/ShapeNet/dataset_10w
    filelist: &filelist data/ShapeNet/filelist/train_airplane.txt
    load_pointcloud: &load_pointcloud True
    load_sdf: &load_sdf False
    batch_size: 1
    shuffle: True

  test:
    name: *name

    # octree building
    depth: *depth
    full_depth: *full_depth
    point_scale: *point_scale

    # sdf & color samples
    volume_sample_num: *volume_sample_num
    surface_sample_num: *surface_sample_num

    # no data augmentation
    distort: *distort

    # data loading
    location: *location
    filelist: *filelist
    batch_size: 1
    load_pointcloud: *load_pointcloud
    load_sdf: *load_sdf
    shuffle: False




MODEL:
  depth: *depth
  full_depth: *full_depth
  depth_stop: 6
  vqvae_ckpt: saved_ckpt/vqvae_model.pth

  VQVAE:
    name: vae

    in_channels: 4
    out_channels: 4
    embedding_sizes: 128
    embedding_channels: 256
    feature: ND
    
  

LOSS:
  name: shapenet_vae_loss
  loss_type: sdf_reg_loss
  vq_weight: 0.5
