BASE:
  - configs/shapenet_vae.yaml

SOLVER:
  logdir: logs/room/room
  max_epoch: 900

  type: adamw
  lr: 0.00025


DATA:
  train:
    name: synthetic_room
    points_scale: &points_scale 0.6

    # data loading
    location: data/room/synthetic_room_dataset
    filelist: data/room/filelist/train.txt
    load_occu: True
    batch_size: 2

  test:
    name: synthetic_room

    points_scale: *points_scale

    # data loading
    location: data/room/synthetic_room_dataset
    filelist: data/room/filelist/val.txt
    load_occu: True
    batch_size: 1
    shuffle: False


LOSS:
  name: room
